//---------------------------------------------------------------------------------------
// Sets the a value
//
// # Params:
//   a: new a-axis vaule
//
// # Returns: itself
//
// # Examples:
//   col.r_set(val)
//
// #See Also
//   g_set(), b_set(), a_set(), rgba_set(), r(), g(), b(), black()
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real a) Color

