//---------------------------------------------------------------------------------------
// Sets the green value
//
// # Params:
//   g: new green vaule
//
// # Returns: itself
//
// # Examples:
//   col.g_set(val)
//
// #See Also
//   r_set(), b_set(), r(), b(), black()
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real g) Color
