//---------------------------------------------------------------------------------------
// Sets the x value
//
// # Params:
//   x: new x-axis vaule
//
// # Returns: itself
//
// # Examples:
//   vec.x_set(val)
//
// #See Also
//   y_set(), z_set(), xyz_set(), x(), y(), z(), zero()
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real x) Vector2

