//---------------------------------------------------------------------------------------
// Sets the z value
//
// # Params:
//   z: new z-axis vaule
//
// # Returns: itself
//
// # Examples:
//   vec.z_set(val)
//
// #See Also
//   x_set(), y_set(), xyz_set(), x(), y(), zero()
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real z) Vector4
