//---------------------------------------------------------------------------------------
// Sets the pitch value
//
// # Params:
//   pitch: new pitch vaule
//
// # Returns: itself
//
// # Examples:
//   angles.pitch_set(val)
//
// #See Also
//   yaw_set(), roll_set(), yaw_pitch_roll_set(), yaw(), roll(), zero()
//
// # Author(s): Markus Breyer
//---------------------------------------------------------------------------------------

(Real pitch) RotationAngles
