//---------------------------------------------------------------------------------------
// Sets the roll value
//
// # Params:
//   roll: new roll vaule
//
// # Returns: itself
//
// # Examples:
//   angles.roll_set(val)
//
// #See Also
//   yaw_set(), pitch_set(), yaw_pitch_roll_set(), yaw(), pitch(), zero()
//
// # Author(s): Markus Breyer
//---------------------------------------------------------------------------------------

(Real roll) RotationAngles
