//---------------------------------------------------------------------------------------
// Get the instantiated actors derived from this class and all subclasses.
//
// Returns:  List of all instances of this class
// Examples: !actors:  Actor.instances%_do_stuff
// See:      named_count(), named(), find_instance(), find_named()
//---------------------------------------------------------------------------------------

() List{ThisClass_}

