//---------------------------------------------------------------------------------------
// Description and Returns true if both Booleans are true.
// Returns     true if both Booleans are true, false if not
// Examples    value1 and value2  // or value1.and(value2)
// Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

(Boolean operand) Boolean

