//---------------------------------------------------------------------------------------
// Sets the blue value
//
// # Params:
//   b: new blue vaule
//
// # Returns: itself
//
// # Examples:
//   col.b_set(val)
//
// #See Also
//   r_set(), g_set(), r(), g(), black()
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real b) Color
