//---------------------------------------------------------------------------------------
// Sets the red value
//
// # Params:
//   r: new red vaule
//
// # Returns: itself
//
// # Examples:
//   col.r_set(val)
//
// #See Also
//   g_set(), b_set(), r(), g(), b(), black()
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real r) Color

