//---------------------------------------------------------------------------------------
// Description Sets the data with the specified name in this scope to the supplied object
// Arg         data_name - name of data to set
// Arg         data - object/instance to set
// Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

(Symbol data_name, Object value)

