//---------------------------------------------------------------------------------------
// Whenever an `ActorEndOverlap` event occurs on this actor, run `code` on it.
// This coroutine never finishes by itself and can only be terminated externally.
//
// See: _on_end_overlap_do_until, _on_begin_overlap_do
//---------------------------------------------------------------------------------------

((Actor actor) code)
