//---------------------------------------------------------------------------------------
// Description Constructor - Set world position/translation and rotation of transform
// Author(s)   Markus Breyer
//---------------------------------------------------------------------------------------

(Vector3 pos, Rotation rot)

  [
  Transform@!()
  position_set(pos)
  rotation_set(rot)
  ]

