//---------------------------------------------------------------------------------------
// Description Constructor - Set world position/translation, rotation and scale of transform
// Author(s)   Markus Breyer
//---------------------------------------------------------------------------------------

(Vector3 pos, Rotation rot, Vector3 scale)

  [
  Transform@!()
  position_set(pos)
  rotation_set(rot)
  scale_set(scale)
  ]