//---------------------------------------------------------------------------------------
// Sets the y value
//
// # Params:
//   y: new y-axis vaule
//
// # Returns: itself
//
// # Examples:
//   vec.y_set(val)
//
// #See Also
//   x_set(), z_set(), xyz_set(), x(), z(), zero()
//
// # Author(s): Conan Reis
//---------------------------------------------------------------------------------------

(Real y) Vector3
