//---------------------------------------------------------------------------------------
// - Description Appends items in variable length group to the end of this list.
// - Notes       This method allows duplicate items.
// - Examples    {0, "one", 2.0}.append_group(3, "four")  // list is now {0, "one", 2.0, 3, "four"}
// - Author(s)   Conan Reis
//---------------------------------------------------------------------------------------

({ItemClass_} list)
// Returns itself
ThisClass_

